# Generated by Django 2.2.3 on 2019-07-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_pages', '0004_auto_20160225_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridpagesection',
            name='media_embed_url',
            field=models.URLField(blank=True, help_text="The URL to a video that you'd like to embed, e.g., https://vimeo.com/121095661."),
        ),
    ]
