# Generated by Django 3.2.9 on 2021-12-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_pages', '0005_auto_20190710_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridpagesection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
