# Generated by Django 3.2.9 on 2021-11-12 17:07

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.core.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('posted', models.DateField(help_text='Date story posted')),
                ('map_link', models.TextField(blank=True, help_text="A Marine Planner map url, or blank if this story isn't connected to a map.", max_length=4096, null=True)),
                ('description', wagtail.core.fields.RichTextField(blank=True, help_text="The article's introductory content. Text here appears in the list of news stories, as well as below the headline and above any section content in the story page.", null=True)),
                ('feature_image', models.ForeignKey(blank=True, help_text='Image displayed on the news story list.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.portalimage')),
            ],
            options={
                'ordering': ('-posted',),
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StorySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('media_embed_url', models.URLField(blank=True, help_text="The URL to a video that you'd like to embed, e.g., https://vimeo.com/121095661.")),
                ('media_caption', models.CharField(blank=True, max_length=255)),
                ('media_position', models.CharField(choices=[('left', 'left'), ('right', 'right'), ('full', 'full')], default='left', max_length=8)),
                ('header', models.CharField(blank=True, max_length=255)),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
                ('media_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.portalimage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_sections', to='news.story')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
