# Generated by Django 2.2.3 on 2019-07-10 00:58

from django.db import migrations, models
from django.conf import settings
if settings.WAGTAIL_VERSION > 1:
    import wagtail.fields as wagtail_core_fields
else:
    import wagtail.fields as wagtail_core_fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20160225_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='description',
            field=wagtail_core_fields.RichTextField(blank=True, help_text="The article's introductory content. Text here appears in the list of news stories, as well as below the headline and above any section content in the story page.", null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='map_link',
            field=models.TextField(blank=True, help_text="A Marine Planner map url, or blank if this story isn't connected to a map.", max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='storysection',
            name='media_embed_url',
            field=models.URLField(blank=True, help_text="The URL to a video that you'd like to embed, e.g., https://vimeo.com/121095661."),
        ),
    ]
