# Generated by Django 3.2.9 on 2021-12-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190710_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storysection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
