# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-05-26 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.models
import wagtail.images.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        # ('wagtailimages', '0015_fill_filter_spec_field'),
        ('base', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='portalimage',
        #     name='collection',
        #     field=models.ForeignKey(default=wagtail.core.models.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Collection', verbose_name='collection'),
        # ),
        # migrations.AddField(
        #     model_name='portalrendition',
        #     name='filter',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Filter'),
        # ),
        # migrations.AddField(
        #     model_name='portalrendition',
        #     name='filter_spec',
        #     field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        # ),
        migrations.AlterField(
            model_name='portalrendition',
            name='file',
            field=models.ImageField(height_field='height', upload_to=wagtail.images.models.get_rendition_upload_to, width_field='width'),
        ),
        migrations.AlterField(
            model_name='portalrendition',
            name='focal_point_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        # migrations.AlterUniqueTogether(
        #     name='portalrendition',
        #     unique_together=set([('image', 'filter', 'focal_point_key')]),
        # ),
    ]
