# Generated by Django 2.2.12 on 2020-05-19 17:17

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
if settings.WAGTAIL_VERSION > 1:
    import wagtail.core.models as wagtail_core_models
else:
    import wagtail.wagtailcore.models as wagtail_core_models


class Migration(migrations.Migration):

    if settings.WAGTAIL_VERSION > 1:
        dependencies = [
            ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
            ('base', '0001_initial'),
        ]

        operations = [
            migrations.AddField(
                model_name='portalimage',
                name='collection',
                field=models.ForeignKey(default=wagtail_core_models.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Collection', verbose_name='collection'),
            ),
        ]
    else:
        dependencies = []
        operations = []
