# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-05-26 23:57
from __future__ import unicode_literals

from django.db import migrations
from wagtail.images.utils import get_fill_filter_spec_migrations

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200526_2354'),
    ]

    forward, reverse = get_fill_filter_spec_migrations('base', 'PortalRendition')
    operations = [
        migrations.RunPython(forward, reverse),
    ]
