# Generated by Django 3.2.25 on 2025-04-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211207_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalimage',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40),
        ),
    ]
