# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-13 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200526_2357'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='portalrendition',
        #     name='filter',
        # ),
        migrations.AlterField(
            model_name='portalrendition',
            name='filter_spec',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='portalrendition',
            name='focal_point_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=16),
        ),
    ]
