# Generated by Django 4.2 on 2024-02-28 18:46

from django.db import migrations
import wagtail.images.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230713_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalrendition',
            name='file',
            field=wagtail.images.models.WagtailImageField(height_field='height', storage=wagtail.images.models.get_rendition_storage, upload_to=wagtail.images.models.get_rendition_upload_to, width_field='width'),
        ),
    ]
