# Generated by Django 2.0.13 on 2020-06-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200613_0023'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='portalimage',
        #     name='file_hash',
        #     field=models.CharField(blank=True, editable=False, max_length=40),
        # ),
    ]
