# Generated by Django 4.2.20 on 2025-04-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_portalrendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalimage',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='description'),
        ),
    ]
