# Generated by Django 3.2.16 on 2022-11-02 00:23

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields

# Thanks to cssidy for the solution to migrate from RichTextField to Stream:
#   https://stackoverflow.com/a/56024999/706797

import json
from wagtail.core.rich_text import RichText

def migrate_rich_text_body_to_stream(apps, schema_editor):
    pagesPage = apps.get_model('pages', 'Page')
    for page in pagesPage.objects.all():
        if page.body.raw_text and not page.body:
            page.body = [('text', RichText(page.body.raw_text))]
            page.save()
        
        if page.has_unpublished_changes:
            for rev in page.revisions.all():
                data = json.loads(rev.content_json)
                body = data['body']
                data['body'] = json.dumps([{
                    "type": "text",
                    "value": body
                }])
                rev.content_json = json.dumps(data)
                rev.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150112_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock()), ('table', wagtail.core.blocks.StreamBlock([('table', wagtail.contrib.table_block.blocks.TableBlock())]))], blank=True, default=None, null=True),
        ),

        migrations.RunPython(migrate_rich_text_body_to_stream),
    ]
