# Generated by Django 3.2.16 on 2022-12-08 22:12

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_page_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock()), ('table', wagtail.core.blocks.StreamBlock([('table', wagtail.contrib.table_block.blocks.TableBlock(table_options={'renderer': 'html'}))]))], blank=True, default=None, null=True),
        ),
    ]
