# Generated by Django 3.2.12 on 2023-07-10 22:05

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_page_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock()), ('table', wagtail.blocks.StreamBlock([('table', wagtail.contrib.table_block.blocks.TableBlock(table_options={'renderer': 'html'}))]))], blank=True, default=None, null=True),
        ),
    ]
