# Generated by Django 4.2 on 2024-05-10 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_menu_slug_menuentry_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='menuentry',
            name='slug',
        ),
    ]
