# Generated by Django 3.2.9 on 2021-11-12 17:07

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='OceanStories',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.core.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='OceanStory',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('display_home_page', models.BooleanField(default=True, help_text='Check to display this ocean story on the home page')),
                ('hook', models.CharField(blank=True, max_length=256, null=True)),
                ('explore_title', models.CharField(blank=True, max_length=256, null=True)),
                ('explore_url', models.URLField(blank=True, max_length=4096, null=True)),
                ('feature_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.portalimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='OceanStorySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('media_embed_url', models.URLField(blank=True, help_text="The URL to a video that you'd like to embed, e.g., https://vimeo.com/121095661.")),
                ('media_caption', models.CharField(blank=True, max_length=255)),
                ('media_position', models.CharField(choices=[('left', 'left'), ('right', 'right'), ('full', 'full')], default='left', max_length=8)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock()), ('raw_html', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True)),
                ('map_state', models.TextField()),
                ('map_legend', models.BooleanField(default=False, help_text="Check to display the map's legend to the right of the the section text.")),
                ('media_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.portalimage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ocean_stories.oceanstory')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
