# Generated by Django 2.2.3 on 2019-11-06 23:58

from django.db import migrations
from django.conf import settings
if settings.WAGTAIL_VERSION > 1:
    import wagtail.core.fields as wagtail_core_fields
    import wagtail.core.blocks as wagtail_core_blocks
else:
    import wagtail.core.fields as wagtail_core_fields
    import wagtail.core.blocks as wagtail_core_blocks


class Migration(migrations.Migration):

    dependencies = [
        ('ocean_stories', '0013_auto_20190710_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='oceanstorysection',
            name='stream_body',
            field=wagtail_core_fields.StreamField([('rich_text', wagtail_core_blocks.RichTextBlock(template='ocean_stories/rich_text_block.html')), ('raw_html', wagtail_core_blocks.RawHTMLBlock())], blank=True, null=True),
        ),
    ]
