# Generated by Django 2.2.3 on 2019-11-06 23:58

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ocean_stories', '0013_auto_20190710_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='oceanstorysection',
            name='stream_body',
            field=wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock(template='ocean_stories/rich_text_block.html')), ('raw_html', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True),
        ),
    ]
