# Generated by Django 2.2.3 on 2019-11-06 23:58

# Wagtail v1 vs. v2 is origional code by Ecotrust

# Logic to migrate from RichText to StreamField comes from:
#  https://cassidybrooke.net/2019/04/03/Migrating-RichTextFields-To-StreamField-In-Wagtail#:~:text=Finally%2C%20we're%20going%20to,converted%20to%20a%20StreamField%20RichTextBlock.

from django.db import migrations
from django.conf import settings
if settings.WAGTAIL_VERSION > 1:
    import wagtail.core.fields as wagtail_core_fields
    import wagtail.core.blocks as wagtail_core_blocks
    from wagtail.core.rich_text import RichText
else:
    import wagtail.wagtailcore.fields as wagtail_core_fields
    import wagtail.wagtailcore.blocks as wagtail_core_blocks
    from wagtail.wagtailcore.rich_text import RichText

def convert_to_streamfield(apps, schema_editor):
    OsSection = apps.get_model("ocean_stories","OceanStorySection")
    for section in OsSection.objects.all():
        if section.body.raw_text and not section.body:
            section.body = [('rich_text', RichText(section.body.raw_text))]
            section.save()

def convert_to_richtext(apps, schema_editor):
    OsSection = apps.get_model("ocean_stories", "OceanStorySection")
    for section in OsSection.objects.all():
        if section.body.raw_text is None:
            raw_text = ''.join([
                child.value.source for child in section.body
                if child.block_type == 'rich_text'
            ])
            section.body = raw_text
            section.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ocean_stories', '0013_auto_20190710_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oceanstorysection',
            name='body',
            field=wagtail_core_fields.StreamField([('rich_text', wagtail_core_blocks.RichTextBlock(template='ocean_stories/rich_text_block.html')), ('raw_html', wagtail_core_blocks.RawHTMLBlock())], blank=True, null=True),
        ),
        migrations.RunPython(
            convert_to_streamfield,
            convert_to_richtext,
        ),
    ]
