# Generated by Django 2.2.3 on 2019-11-07 01:32

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ocean_stories', '0014_oceanstorysection_stream_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oceanstorysection',
            name='stream_body',
            field=wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock()), ('raw_html', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True),
        ),
    ]
