# Generated by Django 2.2.7 on 2019-11-21 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocean_stories', '0015_auto_20191107_0132'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='oceanstorysection',
        #     name='body',
        # ),
    ]
