# Generated by Django 2.2.7 on 2019-11-21 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocean_stories', '0016_remove_oceanstorysection_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oceanstorysection',
            old_name='stream_body',
            new_name='body',
        ),
    ]
