# Generated by Django 3.2.9 on 2021-12-07 00:09

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ocean_stories', '0017_auto_20191121_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oceanstorysection',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock()), ('raw_html', wagtail.blocks.RawHTMLBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oceanstorysection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
