# Generated by Django 3.2.12 on 2023-07-13 20:24

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ocean_stories', '0018_auto_20211207_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oceanstorysection',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock()), ('raw_html', wagtail.blocks.RawHTMLBlock())], blank=True, null=True, use_json_field=True),
        ),
    ]
