# Generated by Django 3.2.9 on 2021-12-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_snippet', '0006_welcomepageentry_media_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomepage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='welcomepageentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
