# Generated by Django 4.2 on 2024-05-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_snippet', '0007_auto_20211216_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomepage',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='welcomepageentry',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
