# Generated by Django 4.2 on 2024-05-15 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_snippet', '0008_welcomepage_slug_welcomepageentry_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welcomepage',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='welcomepageentry',
            name='slug',
        ),
    ]
